# Form implementation generated from reading ui file 'c:\Users\Michael\OneDrive\Desktop\CCC151-find@msuiit\Find-MSUIIT\ui\popups.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


